### ISSUE TITLE
Ability to open record details in the org

### ISSUE THREAD

**Issue by kyunussov** [forcedotcom/soql-tooling#144] opened 2021-01-31 14:03 UTC
Similarly to Developer Console query results - would like the ability to open the record in the default org.

Would need to query ID for that to be possible.  

Specify in settings whether to use Lightning or Classic link type.

**Comment by smaddox-sf** [comment] 2021-02-01 17:27
@kyunussov - Thanks for leaving feedback.  This is a duplicate of #127.  I added your comments to that issue.  Feel free to add further comments there if you have further input on this.  Thanks!

**Closed by smaddox-sf** 2021-02-01 17:27 UTC
