### ISSUE TITLE
Using Ctrl + A or Shift + down arrow or Shift + End does not select all fields in SOQL builder

### ISSUE THREAD

**Issue by davidjbrossard** [forcedotcom/soql-tooling#146] opened 2021-01-31 19:13 UTC
In using the SOQL builder inside Visual Studio Code, I noticed that the way to select fields is odd. The only way that it works is if fields are individually clicked on inside the multi-select UI element. In other words, the items selected in the multi-select are not in fact the ones that will be used. Rather, each field has to be individually clicked. This isn't scalable.

https://user-images.githubusercontent.com/6230719/106395104-4b63e380-63b5-11eb-806c-bdfea075b7fe.mp4

**Comment by smaddox-sf** [comment] 2021-02-01 17:43
Hi @davidjbrossard - Thanks for trying SOQL Builder and giving us feedback!  (The video is helpful!)  This is a duplicate of #89, so I've linked this one there and am closing this issue.  Feel free to add more comments to #89 if you have further input on this.

**Closed by smaddox-sf** 2021-02-01 17:43 UTC
