### ISSUE TITLE
Add ability to edit the query directly

### ISSUE THREAD

**Issue by kyunussov** [forcedotcom/soql-tooling#143] opened 2021-01-31 14:00 UTC
Currently, we click fields, they get added to the query.  
After that, you can't reorder fields. 
The only way to add fields is by scrolling through the Fields list. 

Would be great if you could type field names directly into the "query builder" textbox, in case you want to reorder the fields, or quickly type one in.

**Comment by smaddox-sf** [comment] 2021-02-01 17:24
Hi @kyunussov - Thanks for checking out SOQL Builder and giving feedback.  This is a duplicate of #135 .  Check it out and weigh in if you have further input.

(btw, we'll soon be releasing an update to the Fields & Object selection.  It will let you type to search the dropdown.)

**Closed by smaddox-sf** 2021-02-01 17:24 UTC
