### ISSUE TITLE
Directly editable SOQL query text

### ISSUE THREAD

**Issue by JosephArenas-ACF** [forcedotcom/soql-tooling#220] opened 2021-02-18 23:20 UTC
Creation of a SOQL query is restricted to point-and-clicks and it is not possible to manually type in, edit, or paste SOQL query text.

Please add the capability to manually type in, edit, or paste SOQL query text.

**Comment by smaddox-sf** [comment] 2021-03-04 22:41
Duplicate of #135

**Closed by smaddox-sf** 2021-03-04 22:41 UTC
